import { Movie } from "./models";

export const movieData: Movie[] = [
    {
        mov_id: 101,
        mov_title: "Titanic",
        mov_year: 1997,
        mov_time: 195,
        mov_lang: "English",
        mov_dt_rel: "1997-12-19",
        mov_rel_country: "USA",
    },
    {
        mov_id: 102,
        mov_title: "The Lord of the Rings: The Return of the King",
        mov_year: 2003,
        mov_time: 201,
        mov_lang: "English",
        mov_dt_rel: "2003-12-01",
        mov_rel_country: "USA",
    },
    {
        mov_id: 103,
        mov_title: "Forrest Gump",
        mov_year: 1994,
        mov_time: 142,
        mov_lang: "English",
        mov_dt_rel: "1994-7-6",
        mov_rel_country: "USA",
    },
    {
        mov_id: 104,
        mov_title: "Harry Potter and the Philosopher's Stone",
        mov_year: 2001,
        mov_time: 152,
        mov_lang: "English",
        mov_dt_rel: "2001-11-04",
        mov_rel_country: "UK",
    },
    {
        mov_id: 105,
        mov_title: "Star Wars: Episode IV - A New Hope",
        mov_year: 1977,
        mov_time: 121,
        mov_lang: "English",
        mov_dt_rel: "1977-05-25",
        mov_rel_country: "USA",
    },
    {
        mov_id: 106,
        mov_title: "The Shawshank Redemption",
        mov_year: 1994,
        mov_time: 142,
        mov_lang: "English",
        mov_dt_rel: "1994-09-23",
        mov_rel_country: "USA",
    },
    {
        mov_id: 107,
        mov_title: "The Godfather",
        mov_year: 1972,
        mov_time: 177,
        mov_lang: "English",
        mov_dt_rel: "1972-03-24",
        mov_rel_country: "USA",
    },
    {
        mov_id: 108,
        mov_title: "The Dark Knight",
        mov_year: 2008,
        mov_time: 152,
        mov_lang: "English",
        mov_dt_rel: "2008-07-18",
        mov_rel_country: "USA",
    },
    {
        mov_id: 109,
        mov_title: "Jurassic Park",
        mov_year: 1993,
        mov_time: 127,
        mov_lang: "English",
        mov_dt_rel: "1993-06-11",
        mov_rel_country: "USA",
    },
    {
        mov_id: 110,
        mov_title: "The Matrix",
        mov_year: 1999,
        mov_time: 136,
        mov_lang: "English",
        mov_dt_rel: "1999-03-31",
        mov_rel_country: "USA",
    },
    {
        mov_id: 111,
        mov_title: "The Shawshank Redemption",
        mov_year: 1994,
        mov_time: 142,
        mov_lang: "English",
        mov_dt_rel: "1994-09-10",
        mov_rel_country: "USA",
    },
    {
        mov_id: 112,
        mov_title: "The Dark Knight",
        mov_year: 2008,
        mov_time: 152,
        mov_lang: "English",
        mov_dt_rel: "2008-07-18",
        mov_rel_country: "USA",
    },
    {
        mov_id: 113,
        mov_title: "The Godfather: Part II",
        mov_year: 1974,
        mov_time: 202,
        mov_lang: "English",
        mov_dt_rel: "1974-12-20",
        mov_rel_country: "USA",
    },
    {
        mov_id: 114,
        mov_title: "Schindler's List",
        mov_year: 1993,
        mov_time: 195,
        mov_lang: "English",
        mov_dt_rel: "1993-11-30",
        mov_rel_country: "USA",
    },
    {
        mov_id: 115,
        mov_title: "The Lord of the Rings: The Fellowship of the Ring",
        mov_year: 2001,
        mov_time: 178,
        mov_lang: "English",
        mov_dt_rel: "2001-12-10",
        mov_rel_country: "USA",
    },
    {
        mov_id: 116,
        mov_title: "Psycho",
        mov_year: 1960,
        mov_time: 109,
        mov_lang: "English",
        mov_dt_rel: "1960-06-16",
        mov_rel_country: "USA",
    },
    {
        mov_id: 117,
        mov_title: "The Graduate",
        mov_year: 1967,
        mov_time: 106,
        mov_lang: "English",
        mov_dt_rel: "1967-12-22",
        mov_rel_country: "USA",
    },
    {
        mov_id: 118,
        mov_title: "Alien",
        mov_year: 1979,
        mov_time: 117,
        mov_lang: "English",
        mov_dt_rel: "1979-05-25",
        mov_rel_country: "USA",
    },
    {
        mov_id: 119,
        mov_title: "Goodfellas",
        mov_year: 1990,
        mov_time: 146,
        mov_lang: "English",
        mov_dt_rel: "1990-09-19",
        mov_rel_country: "USA",
    },
    {
        mov_id: 120,
        mov_title: "The Terminator",
        mov_year: 1984,
        mov_time: 107,
        mov_lang: "English",
        mov_dt_rel: "1984-10-26",
        mov_rel_country: "USA",
    },
    {
        mov_id: 121,
        mov_title: "Fight Club",
        mov_year: 1999,
        mov_time: 139,
        mov_lang: "English",
        mov_dt_rel: "1999-10-15",
        mov_rel_country: "USA",
    },
    {
        mov_id: 122,
        mov_title: "The Exorcist",
        mov_year: 1973,
        mov_time: 122,
        mov_lang: "English",
        mov_dt_rel: "1732-12-26",
        mov_rel_country: "USA",
    },
    {
        mov_id: 123,
        mov_title: "Pulp Fiction",
        mov_year: 1994,
        mov_time: 154,
        mov_lang: "English",
        mov_dt_rel: "1994-05-21",
        mov_rel_country: "UK",
    },
    {
        mov_id: 124,
        mov_title: "The Shining",
        mov_year: 1980,
        mov_time: 146,
        mov_lang: "English",
        mov_dt_rel: "1980-06-13",
        mov_rel_country: "USA",
    },
    {
        mov_id: 125,
        mov_title: "The Silence of the Lambs",
        mov_year: 1991,
        mov_time: 118,
        mov_lang: "English",
        mov_dt_rel: "1991-02-14",
        mov_rel_country: "USA",
    },
    {
        mov_id: 126,
        mov_title: "Terminator 2: Judgment Day",
        mov_year: 1991,
        mov_time: 137,
        mov_lang: "English",
        mov_dt_rel: "1991 -07-01",
        mov_rel_country: "USA",
    },
    {
        mov_id: 127,
        mov_title: "Blade Runner",
        mov_year: 1982,
        mov_time: 117,
        mov_lang: "English",
        mov_dt_rel: "1982-06-25",
        mov_rel_country: "USA",
    },
    {
        mov_id: 928,
        mov_title: "Rocky",
        mov_year: 1976,
        mov_time: 119,
        mov_lang: "English",
        mov_dt_rel: "1976-11-21",
        mov_rel_country: "USA",
    },
]