import { Movie } from "./models";

export const movieData: Movie[] = [
    {
        mov_id: 901,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 902,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 903,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
    {
        mov_id: 904,
        mov_title: "The Deer Hunter",
        mov_year: 1978,
        mov_time: 183,
        mov_lang: "English",
        mov_dt_rel: "1979-03-08",
        mov_rel_country: "UK",
    },
    {
        mov_id: 905,
        mov_title: "Amadeus",
        mov_year: 1984,
        mov_time: 160,
        mov_lang: "English",
        mov_dt_rel: "1985-01-07",
        mov_rel_country: "UK",
    },
    {
        mov_id: 906,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 907,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 908,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
    {
        mov_id: 909,
        mov_title: "The Deer Hunter",
        mov_year: 1978,
        mov_time: 183,
        mov_lang: "English",
        mov_dt_rel: "1979-03-08",
        mov_rel_country: "UK",
    },
    {
        mov_id: 910,
        mov_title: "Amadeus",
        mov_year: 1984,
        mov_time: 160,
        mov_lang: "English",
        mov_dt_rel: "1985-01-07",
        mov_rel_country: "UK",
    },
    {
        mov_id: 911,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 912,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 913,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
    {
        mov_id: 914,
        mov_title: "The Deer Hunter",
        mov_year: 1978,
        mov_time: 183,
        mov_lang: "English",
        mov_dt_rel: "1979-03-08",
        mov_rel_country: "UK",
    },
    {
        mov_id: 915,
        mov_title: "Amadeus",
        mov_year: 1984,
        mov_time: 160,
        mov_lang: "English",
        mov_dt_rel: "1985-01-07",
        mov_rel_country: "UK",
    },
    {
        mov_id: 916,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 917,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 918,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
    {
        mov_id: 919,
        mov_title: "The Deer Hunter",
        mov_year: 1978,
        mov_time: 183,
        mov_lang: "English",
        mov_dt_rel: "1979-03-08",
        mov_rel_country: "UK",
    },
    {
        mov_id: 920,
        mov_title: "Amadeus",
        mov_year: 1984,
        mov_time: 160,
        mov_lang: "English",
        mov_dt_rel: "1985-01-07",
        mov_rel_country: "UK",
    },
    {
        mov_id: 921,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 922,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 923,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
    {
        mov_id: 924,
        mov_title: "The Deer Hunter",
        mov_year: 1978,
        mov_time: 183,
        mov_lang: "English",
        mov_dt_rel: "1979-03-08",
        mov_rel_country: "UK",
    },
    {
        mov_id: 925,
        mov_title: "Amadeus",
        mov_year: 1984,
        mov_time: 160,
        mov_lang: "English",
        mov_dt_rel: "1985-01-07",
        mov_rel_country: "UK",
    },
    {
        mov_id: 926,
        mov_title: "Vertigo",
        mov_year: 1958,
        mov_time: 128,
        mov_lang: "English",
        mov_dt_rel: "1958-08-24",
        mov_rel_country: "UK",
    },
    {
        mov_id: 927,
        mov_title: "The Innocents",
        mov_year: 1961,
        mov_time: 100,
        mov_lang: "English",
        mov_dt_rel: "1962-02-19",
        mov_rel_country: "SW",
    },
    {
        mov_id: 928,
        mov_title: "Lawrence of Arabia",
        mov_year: 1962,
        mov_time: 216,
        mov_lang: "English",
        mov_dt_rel: "1962-12-11",
        mov_rel_country: "UK",
    },
]